# Generated by Django 6.0.5 on 2026-05-24 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_programada', models.DateTimeField()),
                ('linea_producto', models.CharField(choices=[('camisetas', 'Camisetas'), ('pantalones', 'Pantalones'), ('zapatos', 'Zapatos'), ('accesorios', 'Accesorios')], max_length=20)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_proceso', 'En proceso'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='terceros.tercero')),
            ],
            options={
                'db_table': 'citas',
                'ordering': ['-fecha_programada'],
                'indexes': [models.Index(fields=['estado'], name='citas_estado_03180e_idx'), models.Index(fields=['proveedor'], name='citas_proveed_600966_idx'), models.Index(fields=['linea_producto'], name='citas_linea_p_075df8_idx'), models.Index(fields=['fecha_programada'], name='citas_fecha_p_7af2d8_idx')],
            },
        ),
    ]
