# Generated by Django 6.0.5 on 2026-05-24 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha_programada']},
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='citas_estado_03180e_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['proveedor'], name='citas_proveed_47fa43_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['linea_producto'], name='citas_linea_p_075df8_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_programada'], name='citas_fecha_p_7af2d8_idx'),
        ),
        migrations.AlterModelTable(
            name='cita',
            table='citas',
        ),
    ]
