# Generated by Django 6.0.5 on 2026-06-11 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_lineaproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='citas_estado_03180e_idx',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='citas_proveed_600966_idx',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='citas_linea_p_075df8_idx',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='citas_fecha_p_7af2d8_idx',
        ),
        migrations.AlterField(
            model_name='cita',
            name='linea_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.lineaproducto'),
        ),
        migrations.AlterModelTable(
            name='cita',
            table=None,
        ),
    ]
