# Generated by Django 6.0.5 on 2026-06-11 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_options_and_more'),
        ('terceros', '0003_alter_tercero_schema_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha_programada']},
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='citas_estado_03180e_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['proveedor'], name='citas_proveed_600966_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['linea_producto'], name='citas_linea_p_e537ee_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_programada'], name='citas_fecha_p_7af2d8_idx'),
        ),
        migrations.AlterModelTable(
            name='cita',
            table='citas',
        ),
    ]
