# Generated by Django 6.0.5 on 2026-05-24 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('proveedor', models.BooleanField(default=False)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula'), ('NIT', 'NIT'), ('CE', 'Cédula Extranjería'), ('PAS', 'Pasaporte')], max_length=10)),
                ('cliente', models.BooleanField(default=False)),
                ('socio', models.BooleanField(default=False)),
                ('tipo_persona', models.CharField(choices=[('N', 'Natural'), ('J', 'Jurídica')], max_length=1)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'terceros',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='terceros_nombre_d2429c_idx'), models.Index(fields=['activo'], name='terceros_activo_d19265_idx'), models.Index(fields=['cliente'], name='terceros_cliente_540103_idx'), models.Index(fields=['proveedor'], name='terceros_proveed_e6e609_idx'), models.Index(fields=['activo', 'cliente'], name='terceros_activo_595bfb_idx'), models.Index(fields=['activo', 'proveedor'], name='terceros_activo_917dbd_idx')],
            },
        ),
    ]
