# Generated by Django 6.0.5 on 2026-06-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_tercero_schema_name_dominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='schema_name',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
