# Generated by Django 6.0.5 on 2026-06-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Línea de producto',
                'verbose_name_plural': 'Líneas de producto',
                'db_table': 'linea_productos',
                'ordering': ['nombre'],
            },
        ),
    ]
