# Generated by Django 6.0.5 on 2026-06-19 03:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionHoraria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('capacidad_maxima', models.PositiveIntegerField()),
                ('citas_ocupadas', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Programación horaria',
                'verbose_name_plural': 'Programaciones horarias',
                'db_table': 'programaciones_horarias',
                'ordering': ['-fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoCita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(max_length=50)),
                ('estado_nuevo', models.CharField(max_length=50)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('usuario_id', models.UUIDField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='citas.cita')),
            ],
            options={
                'verbose_name': 'Historial de estado de cita',
                'verbose_name_plural': 'Historiales de estado de citas',
                'db_table': 'historiales_estado_citas',
                'ordering': ['-fecha'],
            },
        ),
    ]
